### ISSUE TITLE
portal sometimes undefined

### ISSUE THREAD

**Issue by faust64** [LemonLDAPNG/node-lemonldap-ng-handler#4]
Hi,

I'm looking at a weird issue related to the node handler.
Sometimes, I would see traces like the following in my logs:

```
0|front       | router caught error
0|front       | TypeError: this.conf.tsv.portal is not a function                                        
0|front       |     at Handler.goToPortal (/opt/app-root/src/node_modules/node-lemonldap-ng-handler/lib/handler.js:244:28)    
0|front       |     at Handler.run (/opt/app-root/src/node_modules/node-lemonldap-ng-handler/lib/handler.js:62:21)      
0|front       |     at run (/opt/app-root/src/node_modules/node-lemonldap-ng-handler/lib/handler.js:309:16)
0|front       |     at Layer.handle [as handle_request] (/opt/app-root/src/node_modules/express/lib/router/layer.js:95:5)     
0|front       |     at trim_prefix (/opt/app-root/src/node_modules/express/lib/router/index.js:317:13)   
0|front       |     at /opt/app-root/src/node_modules/express/lib/router/index.js:284:7                  
0|front       |     at Function.process_params (/opt/app-root/src/node_modules/express/lib/router/index.js:335:12)      
0|front       |     at next (/opt/app-root/src/node_modules/express/lib/router/index.js:275:10)          
0|front       |     at jsonParser (/opt/app-root/src/node_modules/body-parser/lib/types/json.js:110:7)   
0|front       |     at Layer.handle [as handle_request] (/opt/app-root/src/node_modules/express/lib/router/layer.js:95:5)
```

Using the handler authenticating accesses to some webapp, sometimes my workers would return that error on a loop, and I won't ever be able to authenticate using that worker.
Most of the times, the configuration gets properly loaded and I don't have any issue.

It seems to me this has to do with configuration loading, as a faulty worker would never recover. And I won't ever see workers turning faulty after some time.

Now, adding some debug to the lemonldap-ng-handler library, when conf is properly loaded, I would see the following:

```
2|front       | enters goToPortal, this.conf.tsv has:
2|front       | {
2|front       |   defaultCondition: {
2|front       |     'app.example.com': [Function: sub1],
2|front       |     'app-blue.example.com': [Function: sub2],
2|front       |     'app-green.example.com': [Function: sub3]
2|front       |   },
[...]
2|front       |   port: { _: '443' },
2|front       |   portal: [Function],
2|front       |   vhostAlias: {},
[...]
```

Now, a faulty worker would instead show:
```
0|front       | enters goToPortal, this.conf.tsv has:
0|front       | {
0|front       |   defaultCondition: {},
0|front       |   defaultProtection: {},
0|front       |   forgeHeaders: {},
0|front       |   headerList: {},
0|front       |   https: {},
0|front       |   locationCondition: {},
0|front       |   locationCount: {},
0|front       |   locationProtection: {},
0|front       |   locationRegexp: {},
0|front       |   maintenance: {},
0|front       |   port: {},
0|front       |   portal: '',
0|front       |   vhostAlias: {},
0|front       |   vhostOptions: {}
0|front       | }
```

(note those logs are taken out workers running simultaneously, as PM2 forks. Using the very same code, configuration, libraries)

Similarily, we could dump this.conf. When properly loaded, I would find:
```
2|front       | dumping this.conf:
2|front       | HandlerConf {
2|front       |   lmConf: conf {
2|front       |     confFile: '/opt/app-root/src/lemonldap-ng.ini',
2|front       |     type: 'LDAP',
2|front       |     ldapServer: 'ldaps://openldap-demo:1636',
2|front       |     ldapConfBase: 'ou=lemonldap,ou=config,dc=example,dc=com',
2|front       |     ldapBindDN: 'cn=ssoapp,ou=services,dc=example,dc=com',
[...]
2|front       |   vm: {
2|front       |     Script: [Function: Script],
2|front       |     createContext: [Function: createContext],                                            
2|front       |     createScript: [Function: createScript],                                              
2|front       |     runInContext: [Function: runInContext],
2|front       |     runInNewContext: [Function: runInNewContext],
2|front       |     runInThisContext: [Function: runInThisContext],                                      
2|front       |     isContext: [Function: isContext],
2|front       |     compileFunction: [Function: compileFunction]                                         
2|front       |   },
2|front       |   sa: sessions {
2|front       |     logger: LoggerStd {
2|front       |       error: [Function],                                                                 
2|front       |       warn: [Function],
2|front       |       notice: [Function],                                                                
2|front       |       info: [Function],                                                                  
2|front       |       debug: [Function]                                                                  
2|front       |     }                                                                                    
2|front       |   }                                                                                      
2|front       | }
```

Otherwise, that last `sa` seems to be missing:
```
0|front       | dumping this.conf:
0|front       | HandlerConf {
0|front       |   lmConf: conf {
0|front       |     confFile: '/opt/app-root/src/lemonldap-ng.ini',
0|front       |     type: 'LDAP',
0|front       |     ldapServer: 'ldaps://openldap-demo:1636',
0|front       |     ldapConfBase: 'ou=lemonldap,ou=config,dc=example,dc=com',
0|front       |     ldapBindDN: 'cn=ssoapp,ou=services,dc=example,dc=com',
[...]
0|front       |   vm: {
0|front       |     Script: [Function: Script],
0|front       |     createContext: [Function: createContext],
0|front       |     createScript: [Function: createScript],
0|front       |     runInContext: [Function: runInContext],
0|front       |     runInNewContext: [Function: runInNewContext],
0|front       |     runInThisContext: [Function: runInThisContext],
0|front       |     isContext: [Function: isContext],
0|front       |     compileFunction: [Function: compileFunction]
0|front       |   }
0|front       | }
```

Note: this is using LLNG2, with LDAP backed configuration, and following lemonldap-ng.ini

```
[all]
[configuration]
type                 = LDAP
ldapServer           = ldaps://openldap-demo:1636
ldapConfBase         = ou=lemonldap,ou=config,dc=example,dc=com
ldapBindDN           = cn=ssoapp,ou=services,dc=example,dc=com
ldapBindPassword     = secret
ldapObjectClass      = applicationProcess
ldapAttributeId      = cn
ldapAttributeContent = description
[portal]
[handler]
status              = 0
useRedirectOnError  = 1
[manager]
[node-handler]
nodeVhosts          = app.example.com, app-green.example.com, app-blue.example.com
```

I'm suspecting some timeout got hit waiting for a response from LDAP, or something similar, as currently experimenting with OpenShift 4, which still suffers from some network weirdnesses.

**Comment by guimard** [comment]
`this.conf` should be initialized during startup and never modified after. Two possible cases here:
 * startup initialization failed
 * something reinitialized this.conf
@faust64: do you have more logs to share _(from startup ?)_ ?

**Comment by faust64** [comment]
Sure, though there's nothing much being logged at that point:

```
(node:63) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[debug] No id
CRITCAL: handler initialization failed, exiting
```

The last log being one of mine, after a 3 seconds timer, I would call the handler, eventually crashing my worker if I suspect auth's going to fail. A process manager would then restart it, until reaching the expected state:

```
const handler = require('node-lemonldap-ng-handler');
...
handler.init({ configStorage: { confFile: `${path}/lemonldap-ng.ini` } });
...
const handleError = (e) => {
	if (e instanceof TypeError) {
	    if (e.message.indexOf('this.conf.tsv.portal is not a function') >= 0) {
		logger.error('CRITCAL: handler initialization failed, exiting');
		process.exit(1);
	    } else { logger.info('handler properly initialized'); }
	} else {
	    logger.error('CRITCAL: handler caught with:');
	    logger.error(e);
	    process.exit(1);
	}
    };

try {
    execAsync('sleep 3')
	.then(() => handler.run({ headers: { host: config.pool.srvName } }, {}))
	.then((o) => handleError(o))
	.catch((e) => handleError(e));
} catch(e) { handleError(e) }
```

When everything goes well, I would instead see:

```
[debug] Configuration 1 loaded
[debug] Virtualhosts configured for Node.js: wsweet.master.apps.example.com, wsweet-green.master.apps.example.com, wsweet-blue.master.apps.example.com
[debug] Conf key cda: 0
[debug] Conf key cookieExpiration: +1h
[debug] Conf key cookieName: ssoWsweetMasterLab
[debug] Conf key customFunctions: undefined
[debug] Conf key httpOnly: 1
[debug] Conf key securedCookie: 0
[debug] Conf key timeoutActivity: 0
[debug] Conf key useRedirectOnError: 1
[debug] Conf key useRedirectOnForbidden: 1
[debug] Conf key whatToTrace: _whatToTrace
[debug] Conf key loopBackUrl: undefined
[debug] Compiling rules for wsweet.master.apps.example.com
[debug] Compiling rules for wsweet-blue.master.apps.example.com
[debug] Compiling rules for wsweet-green.master.apps.example.com
[debug] Compiling headers for wsweet.master.apps.intra.example.com
[debug] Compiling headers for wsweet-blue.master.apps.example.com
[debug] Compiling headers for wsweet-green.master.apps.example.com
[debug] No id
[debug] Redirecting to https://auth.master.apps.example.com/?url=Zm9vYmFyCg==
[debug] LDAP session ready
handler properly initialized
```

**Comment by guimard** [comment]
Could you try with 0.5.1 ?

**Comment by faust64** [comment]
No better, and my hack no longer works,:

```
[debug] No id
Configuration is not ready
handler properly initialized
[debug] Get configuration 1 failed
[debug] Can't get configuration: null
[debug] No id
Configuration is not ready
[debug] No id
Configuration is not ready
...
```

**Comment by guimard** [comment]
@faust64: I'm unable to reproduce locally. Could you give me some details ?
 * conf backend
 * type of handler (express or FastCGI server)

**Comment by guimard** [comment]
@faust64: note that you should `require('lemonldap-ng-handler')` instead of "node-lemonldap-ng-handler"

**Comment by faust64** [comment]
LDAP configuration

express handler

I did require lemonldap-ng-handler testing 0.5.1, which was not published under its older name.

**Comment by guimard** [comment]
Which version of node ?

**Comment by faust64** [comment]
12.13.0

**Comment by guimard** [comment]
Yes, if you want to use github master, you should build packages: `grunt`. Npmjs registry packages work here _(not tested yet with LDAP)_

**Comment by guimard** [comment]
I need some time to prepare a valid LDAP env

**Comment by faust64** [comment]
FYI, I'm working with images close to the following:

https://github.com/Worteks/docker-ldap (branch: llng2)
https://github.com/Worteks/docker-lemonldap (branch: llng2)
https://github.com/Worteks/docker-apache (branch: buster - required building the lemonldap image)

I still have a bunch of fixes to publish, though those should already include the basics starting up LLNG2 with LDAP backed configuration+sessions.
Let me know if you need help figuring out how to start those without k8s/OpenShift.

**Comment by faust64** [comment]
gotcha:

```
0|front       | handler get caught
0|front       | Error: Cannot find module 'random-bytes'
0|front       | Require stack:
0|front       | - /opt/app-root/src/node_modules/lemonldap-ng-conf/lib/crypto.js
0|front       | - /opt/app-root/src/node_modules/lemonldap-ng-conf/lib/index.js
0|front       | - /opt/app-root/src/node_modules/lemonldap-ng-handler/lib/conf.js
0|front       | - /opt/app-root/src/node_modules/lemonldap-ng-handler/lib/index.js
0|front       | - /opt/app-root/src/lib/express.js
0|front       | - /opt/app-root/src/workers/front.js
0|front       |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
0|front       |     at Module.Hook._require.Module.require (/opt/app-root/src/.npm-global/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:29)
0|front       |     at require (internal/modules/cjs/helpers.js:74:18)
0|front       |     at Object.<anonymous> (/opt/app-root/src/node_modules/lemonldap-ng-conf/lib/crypto.js:11:9)
0|front       |     at Object.<anonymous> (/opt/app-root/src/node_modules/lemonldap-ng-conf/lib/crypto.js:74:4)
0|front       |     at Module._compile (internal/modules/cjs/loader.js:956:30)
0|front       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
0|front       |     at Module.load (internal/modules/cjs/loader.js:812:32)
0|front       |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
0|front       |     at Module.require (internal/modules/cjs/loader.js:849:19)
0|front       |     at Module.Hook._require.Module.require (/opt/app-root/src/.npm-global/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:39)
0|front       |     at require (internal/modules/cjs/helpers.js:74:18)
0|front       |     at /opt/app-root/src/node_modules/lemonldap-ng-conf/lib/index.js:72:19
0|front       |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
0|front       |   code: 'MODULE_NOT_FOUND',
0|front       |   requireStack: [
0|front       |     '/opt/app-root/src/node_modules/lemonldap-ng-conf/lib/crypto.js',
0|front       |     '/opt/app-root/src/node_modules/lemonldap-ng-conf/lib/index.js',
0|front       |     '/opt/app-root/src/node_modules/lemonldap-ng-handler/lib/conf.js',
0|front       |     '/opt/app-root/src/node_modules/lemonldap-ng-handler/lib/index.js',
0|front       |     '/opt/app-root/src/lib/express.js',
0|front       |     '/opt/app-root/src/workers/front.js'
0|front       |   ]
0|front       | }
```

in lemonldap-ng-conf/lib/index.js, we have somewhere:

```
          })["catch"](function(e) {
console.log('handler get caught');
console.log(e);
            self.logger.error("Get configuration " + args.cfgNum + " failed\n", e);
            return reject(null);
          });
```

The self.logger.error does show a "get configuration 1 failed". Then I don't see the error anywhere.
Adding my console.log, we can see the trace from above.

Installing random-bytes, configuration does load properly.
Not sure it would consistently though. Would keep an eye on this.

**Comment by faust64** [comment]
see LemonLDAPNG/node-lemonldap-ng-handler#5

**Comment by faust64** [comment]
From what I've seen, 0.5.1 does seem to consistently load configuration from LDAP.
Closing. Thanks!
